export const phrasesToSayLoading = [
    "Summoning Jutsu! Loading the characters...",
    "Shadow Clone Jutsu! The characters are being loaded...",
    "Believe it! The characters are being fetched...",
    "Dattebayo! The characters are being downloaded...",
    "Rasengan! Loading... Please wait a moment.",
    "Chidori! Fetching characters from the ninja world...",
    "Shuriken! Loading... Don't blink!",
    "Kage Bunshin no Jutsu! Loading the shinobi data...",
    "Byakugan! Scanning for characters...",
    "Sharingan! Loading... Enhancing visualization...",
    "Ramen Break! Characters are on their way...",
    "Ninjutsu! The characters are being summoned...",
    "IT Jutsu! Compiling character data...",
    "DevOps Jutsu! Automating character loading...",
    "Agile Jutsu! Iteratively fetching characters...",
    "Git Jutsu! Pulling character updates...",
    "Server Jutsu! Serving characters hot and fresh...",
    "Cloud Jutsu! Characters are floating down from the cloud...",
    "Sudo Jutsu! Loading characters with elevated privileges...",
    "404 Jutsu! Searching for missing characters...",
    "404 Genjutsu! Illusion... Characters are loading...",
    "Ramen Genjutsu! Ramen break while loading characters...",
    "Jinchuriki! Loading characters with tailed beast chakra...",
    "IT Ninjutsu! Stealthily fetching characters from the database...",
    "Naruto Run! Characters are racing to load...",
    "Rasengan Genjutsu! Loading characters with spinning energy...",
    "Konoha IT Department! Processing character requests...",
    "Sakura's Strength! Loading characters with determination...",
    "Chunin Exams! Characters are undergoing screening...",
    "Bijuu Mode! Characters are being loaded with immense power...",
    "IT Academy! Training characters to load faster...",
    "Ninjutsu Scroll! Unfolding... Loading characters...",
    "Senjutsu! Characters are being imbued with sage energy...",
    "Jiraiya's Research! Investigating ways to load characters faster...",
    "Tailed Beast Bomb! Characters are exploding onto the screen...",
    "Genjutsu Trap! Characters are caught in a loading illusion...",
    "Sharingan Upgrade! Characters are loading in high definition...",
    "Ramen Shop! Loading characters with extra toppings...",
    "Ninshu! Characters are being connected through loading...",
    "Kakashi's Book! Loading characters while reading Icha Icha...",
    "Sasuke's Revenge! Loading characters with vengeance...",
    "Shikamaru's Strategy! Characters are being loaded with careful planning...",
    "Hokage Orders! Characters are loading as per village decree...",
    "IT Ninjutsu Academy! Training characters to load silently...",
    "Jutsu Research Facility! Experimenting with faster character loading...",
    "Naruto's Dream! Loading characters to fulfill his ninja way...",
    "Kage Summit! Characters are gathering for loading negotiations...",
    "Rasenshuriken! Loading characters with swirling power...",
    "Chunin Promotion! Characters are proving their worth by loading...",
    "Hokage Office! Characters are being loaded under village protection...",
    "Naruto's Promise! Loading characters to keep his word...",
    "Jinchuriki Union! Characters are loading with tailed beast cooperation...",
    "Uchiha Clan! Loading characters with the power of the Sharingan...",
    "Sage Mode Training! Characters are learning to load with nature's energy...",
    "Sannin Showdown! Characters are competing to load faster...",
    "Hinata's Courage! Characters are loading with newfound bravery...",
    "Sakura's Determination! Characters are loading with unwavering resolve...",
    "Rock Lee's Training! Characters are loading with the power of youth...",
    "Chunin Squad! Characters are loading as a team...",
    "Naruto's Shadow Clone! Characters are loading in multiple instances...",
    "Shikamaru's Tactics! Characters are loading with strategic precision...",
    "Ramen Date! Characters are loading while enjoying a bowl of ramen...",
    "Kiba's Pack! Characters are loading with the unity of the pack...",
    "Ino's Mind Transfer! Characters are loading in a mental realm...",
    "Choji's Expansion Jutsu! Characters are loading with increased size...",
    "Tenten's Arsenal! Characters are loading with a variety of weapons...",
    "Neji's Byakugan! Characters are loading with enhanced perception...",
    "Hokage's Legacy! Characters are loading to honor past leaders...",
    "Naruto's Will of Fire! Characters are loading with determination...",
    "Shikamaru's Intellect! Characters are loading with strategic insight...",
    "Sasuke's Sharingan! Characters are loading with visual prowess...",
    "Sakura's Medical Jutsu! Characters are loading with healing energy...",
    "Team 7 Bond! Characters are loading with friendship and teamwork...",
    "Kakashi's Teachings! Characters are loading with ninja wisdom...",
    "Konoha Village! Characters are loading under village protection...",
    "Ninja Way! Characters are loading to follow their dreams...",
    "Leaf Village Anthem! Characters are loading with village pride...",
    "Naruto Uzumaki! Characters are loading with the will of a hero...",
    "Believe It! Characters are loading to prove their worth...",
    "Shinobi Code! Characters are loading with honor and duty...",
    "Ninja Registration! Characters are loading to join the ranks...",
    "Naruto's Ramen! Characters are loading with a taste of home...",
    "Hokage Monument! Characters are loading under the watchful eyes...",
    "Jiraiya's Inspiration! Characters are loading with sage guidance...",
    "Ninja Academy! Characters are loading to become future shinobi...",
    "Sage of Six Paths! Characters are loading with ancient power...",
    "Hokage's Will! Characters are loading to protect the village...",
    "Naruto's Training! Characters are loading to master their skills...",
    "Ninja Alliance! Characters are loading to unite the shinobi world...",
    "Ninja Ranks! Characters are loading to climb the ranks...",
    "Hidden Leaf Village! Characters are loading from the heart of Fire...",
    "Naruto's Journey! Characters are loading on the path of destiny...",
    "Shinobi War! Characters are loading for battle...",
    "Hokage Summit! Characters are loading for village diplomacy...",
    "Ninja Scroll! Characters are loading with ancient secrets...",
    "Naruto's Rasengan! Characters are loading with spiraling energy...",
    "Shinobi Training! Characters are loading to become true ninjas...",
    "Ninja Tools! Characters are loading with specialized gear...",
    "Naruto's Seal! Characters are loading with sealed power...",
    "Shinobi Handbook! Characters are loading"]